apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sadpandaops.serviceAccountName" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "sadpandaops.serviceAccountName" . }}
roleRef:
{{- if .Values.sadpandaops.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.sadpandaops.clusterRole }}
{{- else if .Values.sadpandaops.role }}
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.sadpandaops.role }}
{{- else }}
{{ fail "You need either .Values.sadpandaops.clusterRole or .Values.sadpandaops.role " }}
{{- end -}}
  